defaults: &defaults
  domain: "http://192.168.0.104:3000"
  upload_url: "http://192.168.0.104:3000"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  domain: "http://218.244.157.7:4000"
  upload_url: "http://218.244.157.7:4000"